### PR TITLE
Sdk minor features

### PR DESCRIPTION
**Pull request by artkulak**
1. customField added to SDK and wrappers
2. Added player and weapon GUID to key mapping functionality in MatchData - shortens action stream sent to Getgud
3. Introduced a new MatchCompletionState enum & updated error handling to use MatchCompletionState instead of just marking matches as not interesting

### CODE REVIEW

**Review by leetthewire — APPROVED** [review]
40b20dc3032e65b1ea2dc103eab9643a5ff73054 - Support Player Map in Action stream 

No bugs or problems are found.

Recommendations:
1. This commit doubling std::set<std::string> m_playerGuids; which can be converted to std::vector<std::string> m_playerGuids; and used in a pair with std::to_string(n) where n is an ID (key) of a player and the player's GUID which is already storing in there.

Vector would be better in there because we don't need to sort it each time and iterate through millions of players.

int m_nextPlayerKey = 0; will be m_playerGuids.size();

2. Accessing to an action directly can make a problem of code refactoring in the future, because it will be required to work in the same way with the others or newly implemented actions to take some info. I would recommend to update BaseActionData and create a base function to work with external data. 

Idea of the base function: create something like "influencer id" which will work for all the actions, but id will be null if no one is influenced on it. we will need 2 more functions - set and get influencer id, or add one more parameter to the base function which could be null.

"influencer id" could for for all the actions we have, even for spawn (someone could raise a player) or position (someone could teleport a player)

**Review by leetthewire — APPROVED** [review]
543126a894a4be0ef1af16c33f5a5448807b554a - Support weapon guid mapping to keys 

No bugs or problems are found.

Recommendations:

1. A weapon guid could be an "influencer id" also.
In this case, GetWeaponMapString() will handle for each action how it should be proceed with the instance's data.

**Comment by getgudio** [comment]
1) Regarding m_playerGuids: This is per match, the number of players is capped and usually will not exceed 100, so no issues with performance.

2) Regarding working with actions: The structure of the action will 99.9999% not change, not worth the effort

3) Regarding m_weaponGuids: Same as above.

**Review by leetthewire — COMMENTED** [review]
11aae8fa9cf474228a1905778b833f75914dc0fb - Support custom field for Match 

We don't need StartMatch(std::string gameGuid, std::string matchMode, std::string mapName) in this case.

It is better to compress a match as it works for an action.

**Comment by artkulak** [comment]
> [11aae8f](https://github.com/getgud-io/cpp-getgud-sdk-dev/commit/11aae8fa9cf474228a1905778b833f75914dc0fb) - Support custom field for Match
> 
> We don't need StartMatch(std::string gameGuid, std::string matchMode, std::string mapName) in this case.
> 
> It is better to compress a match as it works for an action.

A custom field is optional, shouldn't we define both constructors in this case?

**Comment by leetthewire** [comment]
> > [11aae8f](https://github.com/getgud-io/cpp-getgud-sdk-dev/commit/11aae8fa9cf474228a1905778b833f75914dc0fb) - Support custom field for Match
> > We don't need StartMatch(std::string gameGuid, std::string matchMode, std::string mapName) in this case.
> > It is better to compress a match as it works for an action.
> 
> A custom field is optional, shouldn't we define both constructors in this case?

We can use it with an empty custom field - StartMatch(gameGuid, matchMode, mapName, "").

**Comment by getgudio** [comment]
> > > [11aae8f](https://github.com/getgud-io/cpp-getgud-sdk-dev/commit/11aae8fa9cf474228a1905778b833f75914dc0fb) - Support custom field for Match
> > > We don't need StartMatch(std::string gameGuid, std::string matchMode, std::string mapName) in this case.
> > > It is better to compress a match as it works for an action.
> > 
> > 
> > A custom field is optional, shouldn't we define both constructors in this case?
> 
> We can use it with an empty custom field - StartMatch(gameGuid, matchMode, mapName, "").

That's why you have overload methods, to avoid making the user insert empty parameters.

**Pull request merged**
